spring:
  datasource:
    url: jdbc:h2:file:~/Spring_boot
    driver-class-name: org.h2.Driver
    username: sa
    password:

  jpa:
    show-sql: true
    hibernate:
       ddl-auto: create-drop

  h2:
    console:
      enabled: true
      path: /h2
  jackson:
    serialization:
      indent-output: true
